# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG Project Name
tagline:          ''
description:      'A 2022 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://zalmquist.github.io"
baseurl:          "/soc401examplewebsite/"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/zalmquist/soc401examplewebsite/
